encrypt-type: # 0：普通， 1：国密
  encrypt-type: 0

group-channel-connections-config:
  caCert: classpath:static/ca.crt
  sslCert: classpath:static/sdk.crt
  sslKey: classpath:static/sdk.key
  all-channel-connections:
    - group-id: 1 #group ID
      connections-str:
        - 127.0.0.1:20200 # node listen_ip:channel_listen_port
        - 127.0.0.1:20201
        - 127.0.0.1:20202 # node listen_ip:channel_listen_port
        - 127.0.0.1:20203

channel-service:
  group-id: 1 # sdk实际连接的群组
  agency-name: agency # 机构名称
