encrypt-type: # 0：普通， 1：国密
  encrypt-type: 0

group-channel-connections-config:
  caCert: classpath:static/ca.crt
  sslCert: classpath:static/node.crt
  sslKey: classpath:static/node.key
  all-channel-connections:
    - group-id: 1 #group ID
      connections-str:
        - 192.168.20.130:20200 # node listen_ip:channel_listen_port
        - 192.168.20.130:20201
    - group-id: 2
      connections-str:
        - 192.168.20.130:20202 # node listen_ip:channel_listen_port
        - 192.168.20.130:20203

channel-service:
  group-id: 1 # sdk实际连接的群组
  agency-name: fisco # 机构名称
